### ISSUE TITLE
Segregate role-common into proper (limited to a particular functionality) fully independent roles

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/ansible-role-common#4]
### What? 

Segregate **role-common** into proper (limited to a particular functionality) fully independent roles:
* role-pkg-mgr (apt) -> https://galaxy.ansible.com/manala/apt
* role-python-pip -> https://galaxy.ansible.com/geerlingguy/pip
* role-hostname-set -> https://galaxy.ansible.com/oefenweb/hostname

```
---
- hostname:
    name: "{{ server_hostname }}"
- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ server_hostname }}'
    state: present
```

### Why? 
- Roles provide a framework for fully independent, or interdependent collections of variables, tasks, files, templates, and modules.
- In Ansible, the role is the primary mechanism for breaking a playbook into multiple files. This simplifies writing complex playbooks, and it makes them easier to reuse. The breaking of playbook allows you to logically break the playbook into reusable components.
- Each role is basically limited to a particular functionality or desired output, with all the necessary steps to provide that result either within that role itself or in other roles listed as dependencies.
